#!/usr/bin/env ANSIBLE_NOCOWS=1 ansible-playbook -i tor.rdkr.uk,
---
- hosts: all
  remote_user: neel
  vars:
    # fqdn
    - fqdn: "tor.rdkr.uk"
    - hostname: "tor"
    # ssh-hardening
    - sftp_enabled: true
    - ssh_allow_users: neel
    # relayor
    - tor_ports:
      - { orport: 443, dirport: 80 }
    - tor_offline_masterkey_dir: /Volumes/tor
    - tor_nickname: rdkr
    - tor_signingkeylifetime_days: 90
    - tor_enableControlSocket: True
    - tor_ContactInfo: <neel AT rdkr DOT uk> 0xBBC1514B34CFB0F10231280F2FC36F0EF7887127
    - tor_RelayBandwidthRate: 3400 KBytes
    - tor_RelayBandwidthBurst: 5000 KBytes
  roles:
    # setup
    - { role: holms.fqdn, tags: ['setup'] }
    - { role: jnv.unattended-upgrades, tags: ['setup'] }
    # hardening
    - { role: dev-sec.os-hardening, become: yes, tags: ['hardening'] }
    - { role: dev-sec.ssh-hardening, become: yes, tags: ['hardening'] }
    # vnstat
    - { role: ypid.vnstat, become: yes, tags: ['vnstat'] }
    # tor relay
    - { role: nusenu.relayor, tags: ['tor'] }
